use crate::{
    counters::AudioCounters,
    policy::DEFAULT_BLOCK_FRAMES,
    source::{SourceBus, SourceLifecycle},
    AudioError, AudioEvent, AudioLimits, AudioPolicy, AudioResult, DecodeResult, Decoder,
};

/// Default mixer block frame count used by the v0 policy.
pub const DEFAULT_MIXER_BLOCK_FRAMES: usize = DEFAULT_BLOCK_FRAMES as usize;

/// Logical fixed-point volume where 256 is unity gain.
#[derive(Clone, Copy, Debug, Eq, Ord, PartialEq, PartialOrd)]
pub struct MixerVolume(u16);

impl MixerVolume {
    /// Silent volume.
    pub const SILENCE: Self = Self(0);
    /// Unity volume.
    pub const UNITY: Self = Self(256);

    /// Creates a logical mixer volume.
    pub const fn new(value: u16) -> Self {
        Self(value)
    }

    /// Returns the underlying fixed-point volume value.
    pub const fn get(self) -> u16 {
        self.0
    }
}

impl Default for MixerVolume {
    fn default() -> Self {
        Self::UNITY
    }
}

/// A fixed-length mono PCM16-equivalent block passed from mixer to backend.
///
/// The block is an abstract backend submission unit. It deliberately exposes
/// samples as a safe slice and never exposes backend-owned buffers or raw
/// pointers.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct MixerBlock<const BLOCK_FRAMES: usize = DEFAULT_MIXER_BLOCK_FRAMES> {
    frames: [i16; BLOCK_FRAMES],
}

impl<const BLOCK_FRAMES: usize> MixerBlock<BLOCK_FRAMES> {
    /// Creates a block from exactly one fixed block of signed mono samples.
    pub const fn new(frames: [i16; BLOCK_FRAMES]) -> Self {
        Self { frames }
    }

    /// Creates a silent block.
    pub const fn silence() -> Self {
        Self {
            frames: [0; BLOCK_FRAMES],
        }
    }

    /// Creates a silent block and validates it against runtime limits.
    pub fn silence_for_limits(limits: AudioLimits) -> AudioResult<Self> {
        Self::validate_limits(limits)?;
        Ok(Self::silence())
    }

    /// Validates that this fixed block length matches the configured limits.
    pub fn validate_limits(limits: AudioLimits) -> AudioResult<()> {
        limits.validate()?;

        if BLOCK_FRAMES == 0 || BLOCK_FRAMES != usize::from(limits.block_frames) {
            return Err(AudioError::InvalidArgument);
        }

        Ok(())
    }

    /// Returns the fixed number of mono frames in this block.
    pub const fn frame_count(&self) -> usize {
        BLOCK_FRAMES
    }

    /// Returns this block as signed mono PCM16-equivalent samples.
    pub const fn as_pcm16_mono(&self) -> &[i16; BLOCK_FRAMES] {
        &self.frames
    }
}

/// Optional deterministic timing sample supplied by the service or tests.
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct MixerTiming {
    /// Elapsed mixer work in implementation-defined deterministic ticks.
    pub elapsed_ticks: u64,
    /// Deadline in the same tick unit. Zero disables late-mix accounting.
    pub deadline_ticks: u64,
}

/// Completion event candidates produced by one mix block.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct MixerOutput<const BLOCK_FRAMES: usize, const MAX_COMPLETIONS: usize> {
    /// Fixed-length block generated by the mixer.
    pub block: MixerBlock<BLOCK_FRAMES>,
    completions: [Option<AudioEvent>; MAX_COMPLETIONS],
    completion_count: usize,
}

impl<const BLOCK_FRAMES: usize, const MAX_COMPLETIONS: usize>
    MixerOutput<BLOCK_FRAMES, MAX_COMPLETIONS>
{
    fn new(block: MixerBlock<BLOCK_FRAMES>) -> Self {
        Self {
            block,
            completions: [None; MAX_COMPLETIONS],
            completion_count: 0,
        }
    }

    fn push_completion(&mut self, event: AudioEvent) {
        if self.completion_count < MAX_COMPLETIONS {
            self.completions[self.completion_count] = Some(event);
            self.completion_count += 1;
        }
    }

    /// Returns completion candidates for sources that reached terminal end.
    pub fn completions(&self) -> &[Option<AudioEvent>; MAX_COMPLETIONS] {
        &self.completions
    }

    /// Returns the number of populated completion candidate entries.
    pub const fn completion_count(&self) -> usize {
        self.completion_count
    }
}

/// Fixed-size mono mixer for PCM16-equivalent source slots.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct Mixer<const BLOCK_FRAMES: usize = DEFAULT_MIXER_BLOCK_FRAMES> {
    policy: AudioPolicy,
    app_volume: MixerVolume,
    master_volume: MixerVolume,
    bgm_volume: MixerVolume,
    sfx_volume: MixerVolume,
}

impl<const BLOCK_FRAMES: usize> Mixer<BLOCK_FRAMES> {
    /// Creates a mixer using a validated audio policy.
    pub fn new(policy: AudioPolicy) -> AudioResult<Self> {
        policy.validate()?;
        MixerBlock::<BLOCK_FRAMES>::validate_limits(policy.limits)?;

        Ok(Self {
            policy,
            app_volume: MixerVolume::new(policy.default_volume),
            master_volume: MixerVolume::new(policy.default_volume),
            bgm_volume: MixerVolume::new(policy.default_volume),
            sfx_volume: MixerVolume::new(policy.default_volume),
        })
    }

    /// Restores volumes to the policy defaults **in place**, reusing this
    /// mixer's storage instead of building a replacement value.
    ///
    /// `AudioService::reset` used to overwrite the mixer with `Mixer::new(..)`;
    /// under LTO that materialized a whole temporary `Mixer` on the caller's
    /// frame, which on the core1 audio worker helped overflow its fixed stack
    /// (KOTO-0186). The policy is immutable after construction and was already
    /// validated then, so this re-derives the same defaults without a temporary
    /// and without re-validating.
    pub fn reset(&mut self) {
        self.app_volume = MixerVolume::new(self.policy.default_volume);
        self.master_volume = MixerVolume::new(self.policy.default_volume);
        self.bgm_volume = MixerVolume::new(self.policy.default_volume);
        self.sfx_volume = MixerVolume::new(self.policy.default_volume);
    }

    /// Sets the app-scoped volume used by subsequent blocks.
    pub fn set_app_volume(&mut self, volume: MixerVolume) -> AudioResult<()> {
        self.validate_volume(volume)?;
        self.app_volume = volume;
        Ok(())
    }

    /// Sets the master volume used by subsequent blocks.
    ///
    /// TODO(KA-M11-002): expose this through the future system/BGM bus policy path.
    #[allow(dead_code)]
    pub fn set_master_volume(&mut self, volume: MixerVolume) -> AudioResult<()> {
        self.validate_volume(volume)?;
        self.master_volume = volume;
        Ok(())
    }

    /// Sets the BGM bus volume used by sequence sources.
    pub fn set_bgm_volume(&mut self, volume: MixerVolume) -> AudioResult<()> {
        self.validate_volume(volume)?;
        self.bgm_volume = volume;
        Ok(())
    }

    /// Sets the SFX bus volume used by clip sources.
    pub fn set_sfx_volume(&mut self, volume: MixerVolume) -> AudioResult<()> {
        self.validate_volume(volume)?;
        self.sfx_volume = volume;
        Ok(())
    }

    /// Mixes one fixed block from active sources without timing diagnostics.
    #[cfg(test)]
    pub fn mix<'a, const MAX_RECORDS: usize, const MAX_ACTIVE: usize, const MAX_QUEUE: usize>(
        &mut self,
        lifecycle: &mut SourceLifecycle<'a, MAX_RECORDS, MAX_ACTIVE, MAX_QUEUE>,
        counters: &mut AudioCounters,
    ) -> AudioResult<MixerOutput<BLOCK_FRAMES, MAX_ACTIVE>> {
        self.mix_with_timing(lifecycle, counters, MixerTiming::default())
    }

    /// Mixes one fixed block and records deterministic timing diagnostics.
    ///
    /// With `ram-hot-mix` this whole per-sample loop (decoders and tone
    /// synthesis inline into it under LTO) executes from SRAM instead of
    /// flash XIP; `inline(never)` pins the section — inlining into a
    /// flash-resident caller would silently discard the placement.
    #[cfg_attr(feature = "ram-hot-mix", link_section = ".data.koto_audio_mix")]
    #[cfg_attr(feature = "ram-hot-mix", inline(never))]
    pub fn mix_with_timing<
        'a,
        const MAX_RECORDS: usize,
        const MAX_ACTIVE: usize,
        const MAX_QUEUE: usize,
    >(
        &mut self,
        lifecycle: &mut SourceLifecycle<'a, MAX_RECORDS, MAX_ACTIVE, MAX_QUEUE>,
        counters: &mut AudioCounters,
        timing: MixerTiming,
    ) -> AudioResult<MixerOutput<BLOCK_FRAMES, MAX_ACTIVE>> {
        self.record_timing(counters, timing);

        let mut accum = [0i64; BLOCK_FRAMES];
        let mut had_active = false;
        let mut ended = [None; MAX_ACTIVE];
        let mut ended_count = 0;

        for active_index in 0..MAX_ACTIVE {
            let Some(active_slot) = lifecycle.active_slot_id_at(active_index) else {
                continue;
            };
            let Some(mix_slot) = lifecycle.active_mix_slot_mut(active_slot)? else {
                continue;
            };

            had_active = true;
            let gain = self.composed_gain(mix_slot.volume, mix_slot.bus);

            for sample in &mut accum {
                match mix_slot.decoder.next_sample() {
                    DecodeResult::Sample(decoded) => {
                        if gain != 0 {
                            let scaled = scale_sample(decoded, gain);
                            *sample = sample.saturating_add(scaled);
                        }
                    }
                    DecodeResult::End => break,
                }
            }

            if mix_slot.decoder.is_ended() && ended_count < MAX_ACTIVE {
                ended[ended_count] = Some(active_slot);
                ended_count += 1;
            }
        }

        if !had_active {
            counters.silence_fill_count = counters.silence_fill_count.saturating_add(1);
        }

        let mut frames = [0i16; BLOCK_FRAMES];
        for (sample, mixed) in frames.iter_mut().zip(accum) {
            *sample = saturate_i64_to_i16(mixed);
        }

        let mut output = MixerOutput::new(MixerBlock::new(frames));
        for active_slot in ended.into_iter().flatten() {
            let event = lifecycle.complete_active_slot(active_slot, counters)?;
            output.push_completion(event.into());
        }

        Ok(output)
    }

    fn validate_volume(self, volume: MixerVolume) -> AudioResult<()> {
        if volume.get() < self.policy.min_volume || volume.get() > self.policy.max_volume {
            return Err(AudioError::InvalidArgument);
        }

        Ok(())
    }

    fn composed_gain(self, source_volume: MixerVolume, bus: SourceBus) -> u64 {
        let source = u64::from(source_volume.get());
        let bus = match bus {
            SourceBus::Sfx => u64::from(self.sfx_volume.get()),
            SourceBus::Bgm => u64::from(self.bgm_volume.get()),
        };
        let app = u64::from(self.app_volume.get());
        let master = u64::from(self.master_volume.get());

        source
            .saturating_mul(bus)
            .saturating_mul(app)
            .saturating_mul(master)
    }

    fn record_timing(self, counters: &mut AudioCounters, timing: MixerTiming) {
        counters.max_mix_time_ticks = counters.max_mix_time_ticks.max(timing.elapsed_ticks);
        if timing.deadline_ticks != 0 && timing.elapsed_ticks > timing.deadline_ticks {
            counters.late_mix_count = counters.late_mix_count.saturating_add(1);
        }
    }
}

impl<const BLOCK_FRAMES: usize> Default for Mixer<BLOCK_FRAMES> {
    fn default() -> Self {
        Self::new(AudioPolicy::default()).expect("default audio policy is valid")
    }
}

fn scale_sample(sample: i16, gain: u64) -> i64 {
    // Unity-to-the-fourth: the divisor for a gain composed of four volume
    // stages (source * bus * app * master).
    const UNITY4: u64 = (MixerVolume::UNITY.get() as u64).pow(4);
    if gain <= UNITY4 {
        // Every v0 policy caps volumes at UNITY (256), so the composed gain is
        // at most 256^4 = 2^32 and `|sample| * gain` fits an i64 (≤ 2^47).
        // This is the audio worker's per-sample hot path: on Cortex-M0+ the
        // previous i128 multiply/divide lowered to software 128-bit calls per
        // sample per source, a dominant share of the mixer tick that showed up
        // as KotoRun SMASH `worker_late`/`underruns` (phase=173). Truncating
        // i64 division by the same constant is bit-identical in this range.
        (i64::from(sample) * gain as i64) / UNITY4 as i64
    } else {
        // Volumes above unity (custom policies) keep the wide arithmetic.
        let scaled = i128::from(sample) * i128::from(gain);
        (scaled / i128::from(UNITY4)) as i64
    }
}

fn saturate_i64_to_i16(value: i64) -> i16 {
    if value > i64::from(i16::MAX) {
        i16::MAX
    } else if value < i64::from(i16::MIN) {
        i16::MIN
    } else {
        value as i16
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{
        source::{SourceRequest, SourceState},
        AudioEventKind, ClipAsset, ClipLoop, DropPolicy, LoopCount,
    };

    type TestLifecycle<'a> = SourceLifecycle<'a, 4, 2, 2>;

    const TEST_BLOCK_FRAMES: usize = 4;

    fn policy() -> AudioPolicy {
        AudioPolicy {
            limits: AudioLimits {
                block_frames: TEST_BLOCK_FRAMES as u16,
                max_sfx_sources: 2,
                source_queue_depth: 2,
                ..AudioLimits::default()
            },
            ..AudioPolicy::default()
        }
    }

    fn lifecycle<'a>() -> TestLifecycle<'a> {
        TestLifecycle::new(policy().limits).unwrap()
    }

    fn payload(samples: &[i16]) -> heapless_payload::Payload {
        heapless_payload::Payload::from_samples(samples)
    }

    fn enqueue_clip<'a>(
        lifecycle: &mut TestLifecycle<'a>,
        counters: &mut AudioCounters,
        payload: &'a [u8],
        samples: u32,
        volume: MixerVolume,
        loop_metadata: ClipLoop,
    ) -> crate::SourceId {
        let mut clip = ClipAsset::pcm16_mono(policy().limits.sample_rate_hz, samples, payload);
        clip.loop_metadata = loop_metadata;
        lifecycle
            .enqueue(
                SourceRequest {
                    clip: Some(clip),
                    volume,
                    ..SourceRequest::default()
                },
                counters,
                DropPolicy::RejectNew,
            )
            .unwrap()
    }

    fn promote_all(lifecycle: &mut TestLifecycle<'_>, counters: &mut AudioCounters) {
        while lifecycle.promote_next(counters).is_some() {}
    }

    #[test]
    fn silence_block_matches_policy_length() {
        let block: MixerBlock = MixerBlock::silence_for_limits(AudioLimits::default()).unwrap();

        assert_eq!(block.frame_count(), DEFAULT_MIXER_BLOCK_FRAMES);
        assert!(block.as_pcm16_mono().iter().all(|sample| *sample == 0));
    }

    #[test]
    fn block_length_validates_against_limits() {
        let mut limits = AudioLimits::default();
        limits.block_frames = 64;

        assert_eq!(
            MixerBlock::<DEFAULT_MIXER_BLOCK_FRAMES>::validate_limits(limits),
            Err(AudioError::InvalidArgument)
        );
    }

    #[test]
    fn inactive_sources_emit_silence_block() {
        let mut mixer = Mixer::<TEST_BLOCK_FRAMES>::new(policy()).unwrap();
        let mut lifecycle = lifecycle();
        let mut counters = AudioCounters::default();

        let output = mixer.mix(&mut lifecycle, &mut counters).unwrap();

        assert_eq!(output.block.as_pcm16_mono(), &[0, 0, 0, 0]);
        assert_eq!(counters.silence_fill_count, 1);
        assert_eq!(output.completion_count(), 0);
    }

    #[test]
    fn single_pcm16_clip_emits_expected_samples() {
        let bytes = payload(&[10, -20, 30, -40]);
        let mut mixer = Mixer::<TEST_BLOCK_FRAMES>::new(policy()).unwrap();
        let mut lifecycle = lifecycle();
        let mut counters = AudioCounters::default();
        enqueue_clip(
            &mut lifecycle,
            &mut counters,
            bytes.as_slice(),
            4,
            MixerVolume::UNITY,
            ClipLoop::None,
        );
        promote_all(&mut lifecycle, &mut counters);

        let output = mixer.mix(&mut lifecycle, &mut counters).unwrap();

        assert_eq!(output.block.as_pcm16_mono(), &[10, -20, 30, -40]);
        assert_ne!(output.block.as_pcm16_mono(), &[0, 0, 0, 0]);
    }

    #[test]
    fn short_clip_completes_at_block_boundary() {
        let bytes = payload(&[1, 2, 3, 4]);
        let mut mixer = Mixer::<TEST_BLOCK_FRAMES>::new(policy()).unwrap();
        let mut lifecycle = lifecycle();
        let mut counters = AudioCounters::default();
        let source_id = enqueue_clip(
            &mut lifecycle,
            &mut counters,
            bytes.as_slice(),
            4,
            MixerVolume::UNITY,
            ClipLoop::None,
        );
        promote_all(&mut lifecycle, &mut counters);

        let output = mixer.mix(&mut lifecycle, &mut counters).unwrap();

        assert_eq!(output.block.as_pcm16_mono(), &[1, 2, 3, 4]);
        assert_eq!(output.completion_count(), 1);
        assert_eq!(
            output.completions()[0],
            Some(AudioEvent::for_source(AudioEventKind::Completed, source_id))
        );
        assert_eq!(lifecycle.state(source_id), Ok(Some(SourceState::Completed)));
        assert_eq!(counters.active_source_count, 0);
    }

    #[test]
    fn clip_shorter_than_block_zero_fills_tail() {
        let bytes = payload(&[11, 22]);
        let mut mixer = Mixer::<TEST_BLOCK_FRAMES>::new(policy()).unwrap();
        let mut lifecycle = lifecycle();
        let mut counters = AudioCounters::default();
        enqueue_clip(
            &mut lifecycle,
            &mut counters,
            bytes.as_slice(),
            2,
            MixerVolume::UNITY,
            ClipLoop::None,
        );
        promote_all(&mut lifecycle, &mut counters);

        let output = mixer.mix(&mut lifecycle, &mut counters).unwrap();

        assert_eq!(output.block.as_pcm16_mono(), &[11, 22, 0, 0]);
        assert_eq!(output.completion_count(), 1);
    }

    #[test]
    fn whole_clip_loop_mixes_until_finite_loop_completion() {
        let bytes = payload(&[3, 4]);
        let mut mixer = Mixer::<TEST_BLOCK_FRAMES>::new(policy()).unwrap();
        let mut lifecycle = lifecycle();
        let mut counters = AudioCounters::default();
        enqueue_clip(
            &mut lifecycle,
            &mut counters,
            bytes.as_slice(),
            2,
            MixerVolume::UNITY,
            ClipLoop::Whole {
                count: LoopCount::Finite(1),
            },
        );
        promote_all(&mut lifecycle, &mut counters);

        let output = mixer.mix(&mut lifecycle, &mut counters).unwrap();

        assert_eq!(output.block.as_pcm16_mono(), &[3, 4, 3, 4]);
        assert_eq!(output.completion_count(), 1);
    }

    #[test]
    fn forward_loop_mixes_expected_range() {
        let bytes = payload(&[1, 2, 3]);
        let mut mixer = Mixer::<TEST_BLOCK_FRAMES>::new(policy()).unwrap();
        let mut lifecycle = lifecycle();
        let mut counters = AudioCounters::default();
        enqueue_clip(
            &mut lifecycle,
            &mut counters,
            bytes.as_slice(),
            3,
            MixerVolume::UNITY,
            ClipLoop::Forward {
                start: 1,
                end: 3,
                count: LoopCount::Finite(1),
            },
        );
        promote_all(&mut lifecycle, &mut counters);

        let output = mixer.mix(&mut lifecycle, &mut counters).unwrap();

        assert_eq!(output.block.as_pcm16_mono(), &[1, 2, 3, 2]);
        assert_eq!(output.completion_count(), 0);
    }

    #[test]
    fn zero_source_volume_is_silent_but_advances_completion() {
        let bytes = payload(&[100, 200, 300, 400]);
        let mut mixer = Mixer::<TEST_BLOCK_FRAMES>::new(policy()).unwrap();
        let mut lifecycle = lifecycle();
        let mut counters = AudioCounters::default();
        enqueue_clip(
            &mut lifecycle,
            &mut counters,
            bytes.as_slice(),
            4,
            MixerVolume::SILENCE,
            ClipLoop::None,
        );
        promote_all(&mut lifecycle, &mut counters);

        let output = mixer.mix(&mut lifecycle, &mut counters).unwrap();

        assert_eq!(output.block.as_pcm16_mono(), &[0, 0, 0, 0]);
        assert_eq!(output.completion_count(), 1);
    }

    #[test]
    fn app_master_source_volume_composes() {
        let bytes = payload(&[1024, -1024, 512, -512]);
        let mut mixer = Mixer::<TEST_BLOCK_FRAMES>::new(policy()).unwrap();
        mixer.set_app_volume(MixerVolume::new(128)).unwrap();
        mixer.set_master_volume(MixerVolume::new(128)).unwrap();
        let mut lifecycle = lifecycle();
        let mut counters = AudioCounters::default();
        enqueue_clip(
            &mut lifecycle,
            &mut counters,
            bytes.as_slice(),
            4,
            MixerVolume::new(128),
            ClipLoop::None,
        );
        promote_all(&mut lifecycle, &mut counters);

        let output = mixer.mix(&mut lifecycle, &mut counters).unwrap();

        assert_eq!(output.block.as_pcm16_mono(), &[128, -128, 64, -64]);
    }

    #[test]
    fn app_master_bus_source_volume_composes() {
        let bytes = payload(&[1024, -1024, 512, -512]);
        let mut mixer = Mixer::<TEST_BLOCK_FRAMES>::new(policy()).unwrap();
        mixer.set_app_volume(MixerVolume::new(128)).unwrap();
        mixer.set_master_volume(MixerVolume::new(128)).unwrap();
        mixer.set_sfx_volume(MixerVolume::new(128)).unwrap();
        let mut lifecycle = lifecycle();
        let mut counters = AudioCounters::default();
        enqueue_clip(
            &mut lifecycle,
            &mut counters,
            bytes.as_slice(),
            4,
            MixerVolume::new(128),
            ClipLoop::None,
        );
        promote_all(&mut lifecycle, &mut counters);

        let output = mixer.mix(&mut lifecycle, &mut counters).unwrap();

        assert_eq!(output.block.as_pcm16_mono(), &[64, -64, 32, -32]);
    }

    #[test]
    fn multi_source_mix_saturates_deterministically() {
        let loud_a = payload(&[30000, -30000, 20000, -20000]);
        let loud_b = payload(&[30000, -30000, 20000, -20000]);
        let mut mixer = Mixer::<TEST_BLOCK_FRAMES>::new(policy()).unwrap();
        let mut lifecycle = lifecycle();
        let mut counters = AudioCounters::default();
        enqueue_clip(
            &mut lifecycle,
            &mut counters,
            loud_a.as_slice(),
            4,
            MixerVolume::UNITY,
            ClipLoop::None,
        );
        enqueue_clip(
            &mut lifecycle,
            &mut counters,
            loud_b.as_slice(),
            4,
            MixerVolume::UNITY,
            ClipLoop::None,
        );
        promote_all(&mut lifecycle, &mut counters);

        let output = mixer.mix(&mut lifecycle, &mut counters).unwrap();

        assert_eq!(
            output.block.as_pcm16_mono(),
            &[i16::MAX, i16::MIN, i16::MAX, i16::MIN]
        );
    }

    #[test]
    fn active_and_queued_counters_are_available_to_mixer_users() {
        let bytes = payload(&[1, 2, 3, 4]);
        let mut lifecycle = lifecycle();
        let mut counters = AudioCounters::default();
        enqueue_clip(
            &mut lifecycle,
            &mut counters,
            bytes.as_slice(),
            4,
            MixerVolume::UNITY,
            ClipLoop::None,
        );

        assert_eq!(counters.queued_source_count, 1);
        assert_eq!(counters.active_source_count, 0);

        lifecycle.promote_next(&mut counters).unwrap();

        assert_eq!(counters.queued_source_count, 0);
        assert_eq!(counters.active_source_count, 1);
    }

    #[test]
    fn mix_timing_updates_max_and_late_counters() {
        let mut mixer = Mixer::<TEST_BLOCK_FRAMES>::new(policy()).unwrap();
        let mut lifecycle = lifecycle();
        let mut counters = AudioCounters::default();

        mixer
            .mix_with_timing(
                &mut lifecycle,
                &mut counters,
                MixerTiming {
                    elapsed_ticks: 7,
                    deadline_ticks: 5,
                },
            )
            .unwrap();
        mixer
            .mix_with_timing(
                &mut lifecycle,
                &mut counters,
                MixerTiming {
                    elapsed_ticks: 3,
                    deadline_ticks: 5,
                },
            )
            .unwrap();

        assert_eq!(counters.max_mix_time_ticks, 7);
        assert_eq!(counters.late_mix_count, 1);
    }

    mod heapless_payload {
        #[derive(Clone, Copy)]
        pub struct Payload {
            bytes: [u8; 16],
            len: usize,
        }

        impl Payload {
            pub fn from_samples(samples: &[i16]) -> Self {
                let mut bytes = [0; 16];
                let mut len = 0;
                for sample in samples {
                    let encoded = sample.to_le_bytes();
                    bytes[len] = encoded[0];
                    bytes[len + 1] = encoded[1];
                    len += 2;
                }

                Self { bytes, len }
            }

            pub fn as_slice(&self) -> &[u8] {
                &self.bytes[..self.len]
            }
        }
    }
}
