[target.thumbv6m-none-eabi]
runner = "elf2uf2-rs -d"
rustflags = [
    "-C",
    "link-arg=--nmagic",
    "-C",
    "link-arg=-Tlink.x",
    "-C",
    "link-arg=-Tlink-rp.x",
]

[target.thumbv8m.main-none-eabihf]
rustflags = [
    "-C",
    "link-arg=--nmagic",
    "-C",
    "link-arg=-Tlink-rp235x.x",
    "-C",
    "link-arg=-Tlink.x",
]
